### ISSUE TITLE
cnxcc: segmentation fault on 2 calls get terminatet - kamailio 4.3.3

### ISSUE THREAD

**Issue by dunst0** [kamailio/kamailio#417]
Log:

```
Nov 25 12:01:23 sip42 kamailio[29215]: INFO: <script>: start - duration: 0
Nov 25 12:01:24 sip42 kamailio[29234]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=1.000000, ca2=0.000000
Nov 25 12:01:24 sip42 kamailio[29218]: INFO: <script>: start - duration: 0 
Nov 25 12:01:25 sip42 kamailio[29234]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=4.000000, ca2=1.000000
Nov 25 12:01:26 sip42 kamailio[29234]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=7.000000, ca2=4.000000
Nov 25 12:01:27 sip42 kamailio[29234]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=9.000000, ca2=7.000000
Nov 25 12:01:28 sip42 kamailio[29234]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=11.000000, ca2=9.000000
Nov 25 12:01:28 sip42 kamailio[29234]: INFO: <script>: [2JR.9RLbmcERvjSelQ5zHRdAONs1pk0V]: call killed
Nov 25 12:01:28 sip42 kamailio[29234]: INFO: <script>: [73tmL4-hk3-50vnsgt19E4rPMMAqHlAG]: call killed
Nov 25 12:01:28 sip42 kamailio[29234]: ERROR: cnxcc [cnxcc_mod.c:1023]: terminate_call(): Error executing dlg_end_dlg command. Return code was [404]
Nov 25 12:01:28 sip42 kamailio[29246]: CRITICAL: <core> [pass_fd.c:275]: receive_fd(): EOF on 45
Nov 25 12:01:28 sip42 kamailio[29187]: ALERT: <core> [main.c:728]: handle_sigs(): child process 29234 exited by a signal 11
Nov 25 12:01:28 sip42 kamailio[29187]: ALERT: <core> [main.c:731]: handle_sigs(): core was not generated
Nov 25 12:01:28 sip42 kamailio[29187]: INFO: <core> [main.c:743]: handle_sigs(): terminating due to SIGCHLD
```

Stacktrace:
```
(gdb) bt full
#0  0x00007f3e25b5cfba in get_hash1_raw (s=0x0, len=0) at ../../hashes.h:109
        p = 0x0
        v = 4284224
        h = 0
#1  0x00007f3e25b5d22d in str_hash_get (ht=0x7f3e26333580, key=0x0, len=0) at ../../str_hash.h:94
        h = 32766
        e = 0x301c31c78
#2  0x00007f3e25b69167 in __free_call (call=0x7f3e2646da00) at cnxcc_mod.c:910
        e = 0x0
        __FUNCTION__ = "__free_call"
#3  0x00007f3e25b68dd5 in terminate_all_calls (credit_data=0x7f3e2646d950) at cnxcc_mod.c:899
        call = 0x7f3e2646da00
        tmp = 0x7f3e2646da00
        __FUNCTION__ = "terminate_all_calls"
#4  0x00007f3e25b5952f in check_calls_by_money (ticks=51698976, param=0x0) at cnxcc_check.c:109
        credit_data = 0x7f3e2646d950
        call = 0x7f3e2646da00
        total_consumed_money = 11
        consumption_diff = 2
        h_entry = 0x7f3e2646d858
        tmp = 0x7f3e26335c00
        tmp_call = 0x7f3e2647d680
        i = 118
        __FUNCTION__ = "check_calls_by_money"
#5  0x00000000005bcf1c in fork_basic_timer (child_id=-1, desc=0x7f3e25b866fd "CNXCC TB TIMER", make_sock=1, f=0x7f3e25b58200 <check_calls_by_money>, param=0x0, interval=1)
    at timer_proc.c:79
        pid = 0
#6  0x00007f3e25b5ffce in __child_init (rank=0) at cnxcc_mod.c:383
        pid = 0
        __FUNCTION__ = "__child_init"
#7  0x00000000005143d4 in init_mod_child (m=0x7f3e315cf8a8, rank=0) at sr_module.c:915
        __FUNCTION__ = "init_mod_child"
#8  0x00000000005146db in init_child (rank=0) at sr_module.c:941
No locals.
#9  0x0000000000505cef in main_loop () at main.c:1654
        i = 4
        pid = 1327
        si = 0x0
        si_desc = "udp receiver child=3 sock=127.0.0.1:5060\000\061\000*>\177\000\000\240.~\264\376\177\000\000\a<\355*>\177\000\000y%p\000\000\000\000\000ȥ3&>\177\000\000\220$\361*>\177\000\000\300(l1>\177\000\000\000\371\360*>\177\000\000\003\000\000\000>\177\000\000\060.~\264\376\177\000\000xBI\000\000\000\000"
        nrprocs = 4
        __FUNCTION__ = "main_loop"
#10 0x000000000050be5a in main (argc=13, argv=0x7ffeb47e3138) at main.c:2553
        cfg_stream = 0x1b9c010
        c = -1
        r = 0
        tmp = 0x7ffeb47e4ee2 ""
        tmp_len = 32574
        port = 846456272
        proto = 0
        options = 0x71cae0 ":f:cm:M:dVIhEeb:l:L:n:vKrRDTN:W:w:t:u:g:P:G:SQ:O:a:A:"
        ret = -1
        seed = 1760074178
        rfd = 4
        debug_save = 0
        debug_flag = 0
        dont_fork_cnt = 0
        n_lst = 0xf63d4e2e
        p = 0x7f3e3273e000 ""
        st = {st_dev = 15, st_ino = 9426, st_nlink = 2, st_mode = 16877, st_uid = 109, st_gid = 114, __pad0 = 0, st_rdev = 0, st_size = 40, st_blksize = 4096, st_blocks = 0, 
          st_atim = {tv_sec = 1448451190, tv_nsec = 195999907}, st_mtim = {tv_sec = 1448451190, tv_nsec = 195999907}, st_ctim = {tv_sec = 1448451190, tv_nsec = 195999907}, 
          __glibc_reserved = {0, 0, 0}}
        __FUNCTION__ = "main"
```

**Comment by miconda** [comment]
I pushed a safety check for this situation in master and 4.3 branches. Not being the developer of the module I am not sure of other possible side effects, but at least this kind of crash situation is handled now.

If the issues appears again, reopen the item.

**Comment by dunst0** [comment]
Thank you for the quick fix. But there seem to be still an error:

Only on call:
```
Nov 25 13:32:03 sip42 kamailio[2221]: INFO: <script>: start - duration: 0
Nov 25 13:32:04 sip42 kamailio[2242]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=1.000000, ca2=0.000000
Nov 25 13:32:05 sip42 kamailio[2242]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=3.000000, ca2=1.000000
Nov 25 13:32:06 sip42 kamailio[2242]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=4.000000, ca2=3.000000
Nov 25 13:32:07 sip42 kamailio[2242]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=5.000000, ca2=4.000000
Nov 25 13:32:08 sip42 kamailio[2242]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=6.000000, ca2=5.000000
Nov 25 13:32:09 sip42 kamailio[2242]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=7.000000, ca2=6.000000
Nov 25 13:32:10 sip42 kamailio[2242]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=8.000000, ca2=7.000000
Nov 25 13:32:11 sip42 kamailio[2242]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=9.000000, ca2=8.000000
Nov 25 13:32:12 sip42 kamailio[2242]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=10.000000, ca2=9.000000
Nov 25 13:32:12 sip42 kamailio[2242]: INFO: <script>: [b8de9ee8badd2a24]: call killed
Nov 25 13:32:14 sip42 kamailio[2256]: CRITICAL: <core> [pass_fd.c:275]: receive_fd(): EOF on 45
Nov 25 13:32:14 sip42 kamailio[2197]: ALERT: <core> [main.c:728]: handle_sigs(): child process 2242 exited by a signal 11
Nov 25 13:32:14 sip42 kamailio[2197]: ALERT: <core> [main.c:731]: handle_sigs(): core was generated
Nov 25 13:32:14 sip42 kamailio[2197]: INFO: <core> [main.c:743]: handle_sigs(): terminating due to SIGCHLD
```

```
(gdb) bt full
#0  0x00007f7669346e2c in _IO_vfprintf_internal (s=s@entry=0x7ffc44b27e20, format=<optimized out>, 
    format@entry=0x7f765d123f60 "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <%.*s>;tag=%.*s\r\nTo: <%.*s>;tag=%.*s\r\nCall-ID: %.*s\r\nCSeq: 1 OPTIONS\r\nContent-Length: 0\r\n\r\n", ap=ap@entry=0x7ffc44b27f48) at vfprintf.c:1642
        len = <optimized out>
        string_malloced = <optimized out>
        step0_jumps = {0, -21408, -10006, -9919, -9825, -9738, -9633, -9357, -8392, -7901, -7780, -7036, -7329, -7232, -6868, -9131, -2198, -2183, -4523, -4438, -1471, -3815, -1799, 
          -4599, -168, -1104, -2074, -7135, -7232, -9460}
        space = 0
        is_short = 0
        use_outdigits = 0
        step1_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, -7901, -7780, -7036, -7329, -7232, -6868, -9131, -2198, -2183, -4523, -4438, -1471, -3815, -1799, -4599, -168, -1104, -2074, -7135, 
          -7232, 0}
        group = 0
        prec = -1
        step2_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -7780, -7036, -7329, -7232, -6868, -9131, -2198, -2183, -4523, -4438, -1471, -3815, -1799, -4599, -168, -1104, -2074, -7135, 
          -7232, 0}
        string = <optimized out>
        left = 0
        is_long_double = 0
        width = 0
        step3a_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -7133, 0, 0, 0, -6868, -9131, -2198, -2183, -4523, 0, 0, 0, 0, -4599, 0, 0, 0, 0, 0, 0}
        alt = 0
        showsign = 0
        is_long = 0
        is_char = 0
        pad = 32 ' '
        step3b_jumps = {0 <repeats 11 times>, -7329, 0, 0, -6868, -9131, -2198, -2183, -4523, -4438, -1471, -3815, -1799, -4599, -168, -1104, -2074, 0, 0, 0}
        step4_jumps = {0 <repeats 14 times>, -6868, -9131, -2198, -2183, -4523, -4438, -1471, -3815, -1799, -4599, -168, -1104, -2074, 0, 0, 0}
        is_negative = <optimized out>
        number = <optimized out>
        base = <optimized out>
        the_arg = {pa_wchar = 4284224 L'\x415f40', pa_int = 4284224, pa_long_int = 4284224, pa_long_long_int = 4284224, pa_u_int = 4284224, pa_u_long_int = 4284224, 
          pa_u_long_long_int = 4284224, pa_double = 2.1166878974885686e-317, pa_long_double = <invalid float value>, 
          pa_string = 0x415f40 <_start> "1\355I\211\321^H\211\342H\203\344\360PTI\307\300", 
          pa_wstring = 0x415f40 <_start> L"\x8949ed31\x89485ed1\xe48348e2\x495450f0\x2f00c0c7\xc748006e\x6e2e90c1\xc7c74800\x506a8b\xfff957e8\xf66f4ff䐟\x9d2eb7b8\x2d485500\x9d2eb0\xef88348\x76e58948렛\x85480000\x5d1174c0\x9d2eb0bf\x66e0ff00\x841f0f", pa_pointer = 0x415f40 <_start>, pa_user = 0x415f40 <_start>}
        spec = 115 's'
        _buffer = {__routine = 0x7ffc44b28740, __arg = 0x7f765da0cdc0, __canceltype = 1570820056, __prev = 0x100000000}
        _avail = <optimized out>
        thousands_sep = 0x0
        grouping = 0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>
        done = 73
        f = 0x7f765d123fac "s>;tag=%.*s\r\nTo: <%.*s>;tag=%.*s\r\nCall-ID: %.*s\r\nCSeq: 1 OPTIONS\r\nContent-Length: 0\r\n\r\n"
        lead_str_end = <optimized out>
        end_of_spec = <optimized out>
        work_buffer = "\020z\262D\374\177\000\000\244\026=fv\177\000\000\000\000\000\000\000\000\000\000 \177\262D\374\177\000\000\320~\262D\374\177\000\000A8=fv\177\000\000HINCRBY  \177\262D\374\177\000\000`z\262D\374\177\000\000\000\000\000\000ber_\260z\262D\374\177\000\000\000\000\000\000nsumZˠ]v\177\000\000\000\000\000\000\000\000\000\000\060\060\060\000\374\177\000\000\372y4iv\177\000\000@_A\000\t\000\000\000=\357Eiv\177\000\000p{\262D\374\177\000\000\006\000\000\000\000\000\000\000@\357Eiv\177\000\000X\024\030\000\000\000\000\000X\024\030\000\000\000\000\000\b\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\020"...
        workstart = 0x0
        workend = 0x7ffc44b27dd8 " ~\262D\374\177"
        ap_save = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7ffc44b28020, reg_save_area = 0x7ffc44b27f60}}
        nspecs_done = 0
        save_errno = <optimized out>
        readonly_format = 0
        args_malloced = 0x0
        specs = <optimized out>
        specs_malloced = false
        jump_table = "\001\000\000\004\000\016\000\006\000\000\a\002\000\003\t\000\005\b\b\b\b\b\b\b\b\b\000\000\000\000\000\000\000\032\000\031\000\023\023\023\000\035\000\000\f\000\000\000\000\000\000\025\000\000\000\000\022\000\r\000\000\000\000\000\000\032\000\024\017\023\023\023\n\017\034\000\v\030\027\021\026\f\000\025\033\020\000\000\022\000\r"
        __PRETTY_FUNCTION__ = "_IO_vfprintf_internal"
#1  0x00007f766936845b in __IO_vsprintf (string=0x7f765d327a40 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <", 
    format=0x7f765d123f60 "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <%.*s>;tag=%.*s\r\nTo: <%.*s>;tag=%.*s\r\nCall-ID: %.*s\r\nCSeq: 1 OPTIONS\r\nContent-Length: 0\r\n\r\n", args=args@entry=0x7ffc44b27f48) at iovsprintf.c:42
        sf = {_sbf = {_f = {_flags = -72515583, _IO_read_ptr = 0x7f765d327a40 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <", 
              _IO_read_end = 0x7f765d327a40 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <", 
              _IO_read_base = 0x7f765d327a40 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <", 
              _IO_write_base = 0x7f765d327a40 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <", 
              _IO_write_ptr = 0x7f765d327a89 <_faked_sip_msg_buf+73> "", _IO_write_end = 0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>, 
              _IO_buf_base = 0x7f765d327a40 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <", 
              _IO_buf_end = 0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>, _IO_save_base = 0x0, _IO_backup_base = 0x0, _IO_save_end = 0x0, 
              _markers = 0x0, _chain = 0x0, _fileno = 1, _flags2 = 0, _old_offset = 140146547644704, _cur_column = 0, _vtable_offset = 0 '\000', _shortbuf = "", _lock = 0x0, 
              _offset = 4284224, _codecvt = 0x7f7669ad4325 <_dl_runtime_resolve+53>, _wide_data = 0xffffffffffffffff, _freeres_list = 0x0, _freeres_buf = 0x1, _freeres_size = 1, 
              _mode = -1, _unused2 = "\000\000\000\000@\207\262D\374\177\000\000\000\000\000\000\000\000\000"}, vtable = 0x7f766969e760 <_IO_str_jumps>}, _s = {_allocate_buffer = 0x0, 
            _free_buffer = 0x575961 <run_actions+1572>}}
        ret = <optimized out>
#2  0x00007f766934cf17 in __sprintf (s=<optimized out>, format=<optimized out>) at sprintf.c:32
        arg = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7ffc44b28020, reg_save_area = 0x7ffc44b27f60}}
        done = 0
#3  0x00007f765d115ac9 in faked_msg_init_with_dlg_info (callid=0x7f765d9dd940, from_uri=0x7f765d9dd950, from_tag=0x7f765d9dd960, to_uri=0x7f765d9dd970, to_tag=0x7f765d9dd980, 
    msg=0x7ffc44b280d8) at cnxcc_sip_msg_faker.c:40
        __FUNCTION__ = "faked_msg_init_with_dlg_info"
#4  0x00007f765d100f42 in terminate_call (call=0x7f765d9dd8e0) at cnxcc_mod.c:980
        dmsg = 0x0
        data = 0x7f765d9dd940
        __FUNCTION__ = "terminate_call"
        root = 0x7f765d5f0528
        result = 0x0
        node = 0x1
        node1 = 0x0
        end_dlg_cmd = 0x0
#5  0x00007f765d0ffe09 in terminate_all_calls (credit_data=0x7f765d9dd830) at cnxcc_mod.c:898
        call = 0x7f765d9dd8e0
        tmp = 0x7f765d11d076
        __FUNCTION__ = "terminate_all_calls"
#6  0x00007f765d0f056f in check_calls_by_money (ticks=10250262, param=0x0) at cnxcc_check.c:109
        credit_data = 0x7f765d9dd830
        call = 0x7f765d9dd8e0
        total_consumed_money = 10
        consumption_diff = 1
        h_entry = 0x7f765d9dd738
        tmp = 0x7f765d8ccbe0
        tmp_call = 0x7f765d9ddac0
        i = 116
        __FUNCTION__ = "check_calls_by_money"
#7  0x00000000005bcf1c in fork_basic_timer (child_id=-1, desc=0x7f765d11d75d "CNXCC TB TIMER", make_sock=1, f=0x7f765d0ef240 <check_calls_by_money>, param=0x0, interval=1)
    at timer_proc.c:79
        pid = 0
#8  0x00007f765d0f700e in __child_init (rank=0) at cnxcc_mod.c:383
        pid = 0
        __FUNCTION__ = "__child_init"
#9  0x00000000005143d4 in init_mod_child (m=0x7f7668b668a8, rank=0) at sr_module.c:915
        __FUNCTION__ = "init_mod_child"
#10 0x00000000005146db in init_child (rank=0) at sr_module.c:941
No locals.
#11 0x0000000000505cef in main_loop () at main.c:1654
        i = 4
        pid = 2232
        si = 0x0
        si_desc = "udp receiver child=3 sock=127.0.0.1:5060\000\061\000bv\177\000\000\260\204\262D\374\177\000\000\a\254Fbv\177\000\000y%p\000\000\000\000\000\310\025\215]v\177\000\000\220\224Jbv\177\000\000\300\230\305hv\177\000\000\000iJbv\177\000\000\003\000\000\000v\177\000\000@\204\262D\374\177\000\000xBI\000\000\000\000"
        nrprocs = 4
        __FUNCTION__ = "main_loop"
#12 0x000000000050be5a in main (argc=13, argv=0x7ffc44b28748) at main.c:2553
        cfg_stream = 0xba7010
        c = -1
        r = 0
        tmp = 0x7ffc44b29ee2 ""
        tmp_len = 32630
        port = 1775064528
        proto = 0
        options = 0x71cae0 ":f:cm:M:dVIhEeb:l:L:n:vKrRDTN:W:w:t:u:g:P:G:SQ:O:a:A:"
        ret = -1
        seed = 3907227680
        rfd = 4
        debug_save = 0
        debug_flag = 0
        dont_fork_cnt = 0
        n_lst = 0xf63d4e2e
        p = 0x7f7669cd5000 ""
        st = {st_dev = 15, st_ino = 9426, st_nlink = 2, st_mode = 16877, st_uid = 109, st_gid = 114, __pad0 = 0, st_rdev = 0, st_size = 40, st_blksize = 4096, st_blocks = 0, 
          st_atim = {tv_sec = 1448452079, tv_nsec = 887991422}, st_mtim = {tv_sec = 1448451735, tv_nsec = 331994708}, st_ctim = {tv_sec = 1448451735, tv_nsec = 331994708}, 
          __glibc_reserved = {0, 0, 0}}
        __FUNCTION__ = "main"
```

And with two calls:
```
Nov 25 13:40:13 sip42 kamailio[2353]: INFO: <script>: start - duration: 0
Nov 25 13:40:14 sip42 kamailio[2372]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=1.000000, ca2=0.000000
Nov 25 13:40:14 sip42 kamailio[2357]: INFO: <script>: start - duration: 0
Nov 25 13:40:15 sip42 kamailio[2372]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=2.000000, ca2=1.000000
Nov 25 13:40:16 sip42 kamailio[2372]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=6.000000, ca2=2.000000
Nov 25 13:40:17 sip42 kamailio[2372]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=8.000000, ca2=6.000000
Nov 25 13:40:18 sip42 kamailio[2372]: INFO: cnxcc [cnxcc_check.c:93]: check_calls_by_money(): ec=0.000000, ca=10.000000, ca2=8.000000
Nov 25 13:40:21 sip42 kamailio[2384]: CRITICAL: <core> [pass_fd.c:275]: receive_fd(): EOF on 45
Nov 25 13:40:21 sip42 kamailio[2326]: ALERT: <core> [main.c:728]: handle_sigs(): child process 2372 exited by a signal 11
Nov 25 13:40:21 sip42 kamailio[2326]: ALERT: <core> [main.c:731]: handle_sigs(): core was generated
Nov 25 13:40:21 sip42 kamailio[2326]: INFO: <core> [main.c:743]: handle_sigs(): terminating due to SIGCHLD
Nov 25 13:40:21 sip42 kamailio[2383]: INFO: <core> [main.c:798]: sig_usr(): signal 15 received
Nov 25 13:40:21 sip42 kamailio[2360]: INFO: <core> [main.c:798]: sig_usr(): signal 15 received
Nov 25 13:40:21 sip42 kamailio[2326]: WARNING: tm [h_table.c:130]: free_cell_helper(): removed cell 0x7febbf483c18 is still linked in hash table (h_table.c:440)
Nov 25 13:40:21 sip42 kamailio[2326]: WARNING: tm [h_table.c:130]: free_cell_helper(): removed cell 0x7febbf47fa60 is still linked in hash table (h_table.c:440)
Nov 25 13:40:21 sip42 kamailio[2326]: WARNING: tm [h_table.c:130]: free_cell_helper(): removed cell 0x7febbf47b0d0 is still linked in hash table (h_table.c:440)
Nov 25 13:40:21 sip42 kamailio[2326]: WARNING: tm [h_table.c:130]: free_cell_helper(): removed cell 0x7febbf47ca78 is still linked in hash table (h_table.c:440)
Nov 25 13:40:21 sip42 kamailio[2326]: WARNING: tm [h_table.c:130]: free_cell_helper(): removed cell 0x7febbf47e3b8 is still linked in hash table (h_table.c:440)
Nov 25 13:40:21 sip42 kamailio[2326]: WARNING: tm [h_table.c:130]: free_cell_helper(): removed cell 0x7febbf481108 is still linked in hash table (h_table.c:440)
```

```
(gdb) bt full
#0  strnlen () at ../sysdeps/x86_64/strlen.S:103
No locals.
#1  0x00007febcada7b79 in _IO_vfprintf_internal (s=s@entry=0x7fffb9cb1740, format=<optimized out>, 
    format@entry=0x7febbeb84f60 "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <%.*s>;tag=%.*s\r\nTo: <%.*s>;tag=%.*s\r\nCall-ID: %.*s\r\nCSeq: 1 OPTIONS\r\nContent-Length: 0\r\n\r\n", ap=ap@entry=0x7fffb9cb1868) at vfprintf.c:1642
        len = <optimized out>
        string_malloced = <optimized out>
        step0_jumps = {0, -21408, -10006, -9919, -9825, -9738, -9633, -9357, -8392, -7901, -7780, -7036, -7329, -7232, -6868, -9131, -2198, -2183, -4523, -4438, -1471, -3815, -1799, 
          -4599, -168, -1104, -2074, -7135, -7232, -9460}
        space = 0
        is_short = 0
        use_outdigits = 0
        step1_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, -7901, -7780, -7036, -7329, -7232, -6868, -9131, -2198, -2183, -4523, -4438, -1471, -3815, -1799, -4599, -168, -1104, -2074, -7135, 
          -7232, 0}
        group = 0
        prec = -891647494
        step2_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -7780, -7036, -7329, -7232, -6868, -9131, -2198, -2183, -4523, -4438, -1471, -3815, -1799, -4599, -168, -1104, -2074, -7135, 
          -7232, 0}
        string = <optimized out>
        left = 0
        is_long_double = 0
        width = 0
        step3a_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -7133, 0, 0, 0, -6868, -9131, -2198, -2183, -4523, 0, 0, 0, 0, -4599, 0, 0, 0, 0, 0, 0}
        alt = 0
        showsign = 0
        is_long = 0
        is_char = 0
        pad = 32 ' '
        step3b_jumps = {0 <repeats 11 times>, -7329, 0, 0, -6868, -9131, -2198, -2183, -4523, -4438, -1471, -3815, -1799, -4599, -168, -1104, -2074, 0, 0, 0}
        step4_jumps = {0 <repeats 14 times>, -6868, -9131, -2198, -2183, -4523, -4438, -1471, -3815, -1799, -4599, -168, -1104, -2074, 0, 0, 0}
        is_negative = <optimized out>
        number = <optimized out>
        base = <optimized out>
        the_arg = {pa_wchar = 4284224 L'\x415f40', pa_int = 4284224, pa_long_int = 4284224, pa_long_long_int = 4284224, pa_u_int = 4284224, pa_u_long_int = 4284224, 
          pa_u_long_long_int = 4284224, pa_double = 2.1166878974885686e-317, pa_long_double = <invalid float value>, 
          pa_string = 0x415f40 <_start> "1\355I\211\321^H\211\342H\203\344\360PTI\307\300", 
          pa_wstring = 0x415f40 <_start> L"\x8949ed31\x89485ed1\xe48348e2\x495450f0\x2f00c0c7\xc748006e\x6e2e90c1\xc7c74800\x506a8b\xfff957e8\xf66f4ff䐟\x9d2eb7b8\x2d485500\x9d2eb0\xef88348\x76e58948렛\x85480000\x5d1174c0\x9d2eb0bf\x66e0ff00\x841f0f", pa_pointer = 0x415f40 <_start>, pa_user = 0x415f40 <_start>}
        spec = 46 '.'
        _buffer = {__routine = 0x7fffb9cb2060, __arg = 0x7febbf47fa60, __canceltype = -1085801352, __prev = 0x100000000}
        _avail = <optimized out>
        thousands_sep = 0x0
        grouping = 0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>
        done = 73
        f = 0x7febbeb84fac "s>;tag=%.*s\r\nTo: <%.*s>;tag=%.*s\r\nCall-ID: %.*s\r\nCSeq: 1 OPTIONS\r\nContent-Length: 0\r\n\r\n"
        lead_str_end = <optimized out>
        end_of_spec = <optimized out>
        work_buffer = "0\023˹\377\177\000\000\244&\343\307\353\177\000\000\000\000\000\000\000\000\000\000@\030˹\377\177\000\000\360\027˹\377\177\000\000AH\343\307\353\177\000\000sip:5.15@\030˹\377\177\000\000\200\023˹\377\177\000\000\000\000\000\000ber_\320\023˹\377\177\000\000\000\000\000\000nsum\332\004G\277\353\177\000\000\000\000\000\000\000\000\000\000\060\060\000\000\377\177\000\000\372\211\332\312\353\177\000\000sip:+49402000@5.159.60.157:45850;ob\312\353\177\000\000X\024\030\000\000\000\000\000X\024\030\000\000\000\000\000\b\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\020", '\000' <repeats 11 times>...
        workstart = 0x7feb7ccfc010 ""
        workend = 0x7febb7fff860 ""
        ap_save = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffb9cb1940, reg_save_area = 0x7fffb9cb1880}}
        nspecs_done = 0
        save_errno = <optimized out>
        readonly_format = 0
        args_malloced = 0x0
        specs = <optimized out>
        specs_malloced = false
        jump_table = "\001\000\000\004\000\016\000\006\000\000\a\002\000\003\t\000\005\b\b\b\b\b\b\b\b\b\000\000\000\000\000\000\000\032\000\031\000\023\023\023\000\035\000\000\f\000\000\000\000\000\000\025\000\000\000\000\022\000\r\000\000\000\000\000\000\032\000\024\017\023\023\023\n\017\034\000\v\030\027\021\026\f\000\025\033\020\000\000\022\000\r"
        __PRETTY_FUNCTION__ = "_IO_vfprintf_internal"
#2  0x00007febcadc945b in __IO_vsprintf (string=0x7febbed88a40 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <", 
    format=0x7febbeb84f60 "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <%.*s>;tag=%.*s\r\nTo: <%.*s>;tag=%.*s\r\nCall-ID: %.*s\r\nCSeq: 1 OPTIONS\r\nContent-Length: 0\r\n\r\n", args=args@entry=0x7fffb9cb1868) at iovsprintf.c:42
        sf = {_sbf = {_f = {_flags = -72515583, _IO_read_ptr = 0x7febbed88a40 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <", 
              _IO_read_end = 0x7febbed88a40 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <", 
              _IO_read_base = 0x7febbed88a40 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <", 
              _IO_write_base = 0x7febbed88a40 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <", 
              _IO_write_ptr = 0x7febbed88a89 <_faked_sip_msg_buf+73> "", _IO_write_end = 0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>, 
              _IO_buf_base = 0x7febbed88a40 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <", 
              _IO_buf_end = 0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>, _IO_save_base = 0x0, _IO_backup_base = 0x0, _IO_save_end = 0x0, 
              _markers = 0x0, _chain = 0x0, _fileno = 1, _flags2 = 0, _old_offset = 0, _cur_column = 0, _vtable_offset = -128 '\200', _shortbuf = "", _lock = 0x0, _offset = 1047824, 
              _codecvt = 0x181f48, _wide_data = 0xffffffffffffffff, _freeres_list = 0x0, _freeres_buf = 0x2, _freeres_size = 1, _mode = -1, 
              _unused2 = "\000\000\000\000` ˹\377\177\000\000\000\000\000\000\000\000\000"}, vtable = 0x7febcb0ff760 <_IO_str_jumps>}, _s = {_allocate_buffer = 0x0, 
            _free_buffer = 0x575961 <run_actions+1572>}}
        ret = <optimized out>
#3  0x00007febcadadf17 in __sprintf (s=<optimized out>, format=<optimized out>) at sprintf.c:32
        arg = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffb9cb1940, reg_save_area = 0x7fffb9cb1880}}
        done = 808333344
#4  0x00007febbeb76ac9 in faked_msg_init_with_dlg_info (callid=0x7febbf46a8c0, from_uri=0x7febbf46a8d0, from_tag=0x7febbf46a8e0, to_uri=0x7febbf46a8f0, to_tag=0x7febbf46a900, 
    msg=0x7fffb9cb19f8) at cnxcc_sip_msg_faker.c:40
        __FUNCTION__ = "faked_msg_init_with_dlg_info"
#5  0x00007febbeb61f42 in terminate_call (call=0x7febbf46a860) at cnxcc_mod.c:980
        dmsg = 0x0
        data = 0x7febbf46a8c0
        __FUNCTION__ = "terminate_call"
        root = 0x7febbf051528
        result = 0x0
        node = 0x1
        node1 = 0x0
        end_dlg_cmd = 0x0
#6  0x00007febbeb60e09 in terminate_all_calls (credit_data=0x7febbf46a7b0) at cnxcc_mod.c:898
        call = 0x7febbf46a860
        tmp = 0x7febbf46a860
        __FUNCTION__ = "terminate_all_calls"
#7  0x00007febbeb5156f in check_calls_by_money (ticks=49027574, param=0x0) at cnxcc_check.c:109
        credit_data = 0x7febbf46a7b0
        call = 0x7febbf46a860
        total_consumed_money = 10
        consumption_diff = 2
        h_entry = 0x7febbf46a6b8
        tmp = 0x7febbf32dc00
        tmp_call = 0x7febbf471178
        i = 118
        __FUNCTION__ = "check_calls_by_money"
#8  0x00000000005bcf1c in fork_basic_timer (child_id=-1, desc=0x7febbeb7e75d "CNXCC TB TIMER", make_sock=1, f=0x7febbeb50240 <check_calls_by_money>, param=0x0, interval=1)
    at timer_proc.c:79
        pid = 0
#9  0x00007febbeb5800e in __child_init (rank=0) at cnxcc_mod.c:383
        pid = 0
        __FUNCTION__ = "__child_init"
#10 0x00000000005143d4 in init_mod_child (m=0x7febca5c78a8, rank=0) at sr_module.c:915
        __FUNCTION__ = "init_mod_child"
#11 0x00000000005146db in init_child (rank=0) at sr_module.c:941
No locals.
#12 0x0000000000505cef in main_loop () at main.c:1654
        i = 4
        pid = 2360
        si = 0x0
        si_desc = "udp receiver child=3 sock=127.0.0.1:5060\000\061\000\303\353\177\000\000\320\035˹\377\177\000\000\a\274\354\303\353\177\000\000y%p\000\000\000\000\000\310%3\277\353\177\000\000\220\244\360\303\353\177\000\000\300\250k\312\353\177\000\000\000y\360\303\353\177\000\000\003\000\000\000\353\177\000\000`\035˹\377\177\000\000xBI\000\000\000\000"
        nrprocs = 4
        __FUNCTION__ = "main_loop"
#13 0x000000000050be5a in main (argc=13, argv=0x7fffb9cb2068) at main.c:2553
        cfg_stream = 0x2428010
        c = -1
        r = 0
        tmp = 0x7fffb9cb2ee2 ""
        tmp_len = 32747
        port = -881629744
        proto = 0
        options = 0x71cae0 ":f:cm:M:dVIhEeb:l:L:n:vKrRDTN:W:w:t:u:g:P:G:SQ:O:a:A:"
        ret = -1
        seed = 3581825104
        rfd = 4
        debug_save = 0
        debug_flag = 0
        dont_fork_cnt = 0
        n_lst = 0xf63d4e2e
        p = 0x7febcb736000 ""
        st = {st_dev = 15, st_ino = 9426, st_nlink = 2, st_mode = 16877, st_uid = 109, st_gid = 114, __pad0 = 0, st_rdev = 0, st_size = 40, st_blksize = 4096, st_blocks = 0, 
          st_atim = {tv_sec = 1448452079, tv_nsec = 887991422}, st_mtim = {tv_sec = 1448454734, tv_nsec = 611966105}, st_ctim = {tv_sec = 1448454734, tv_nsec = 611966105}, 
          __glibc_reserved = {0, 0, 0}}
        __FUNCTION__ = "main"
```

**Comment by miconda** [comment]
Pushed another safety check for the new case.

**Comment by dunst0** [comment]
First of all thank you for the time you spent.
Are there any documentation about how module ares written for kamailio that i can help debugging.

The error still exists
```
Nov 25 14:25:38 sip42 kamailio[3093]: CRITICAL: <core> [pass_fd.c:275]: receive_fd(): EOF on 45
Nov 25 14:25:38 sip42 kamailio[3035]: ALERT: <core> [main.c:728]: handle_sigs(): child process 3082 exited by a signal 11
Nov 25 14:25:38 sip42 kamailio[3035]: ALERT: <core> [main.c:731]: handle_sigs(): core was generated
Nov 25 14:25:38 sip42 kamailio[3035]: INFO: <core> [main.c:743]: handle_sigs(): terminating due to SIGCHLD
Nov 25 14:25:38 sip42 kamailio[3093]: INFO: <core> [main.c:798]: sig_usr(): signal 15 received
Nov 25 14:25:38 sip42 kamailio[3088]: INFO: <core> [main.c:798]: sig_usr(): signal 15 received
Nov 25 14:25:38 sip42 kamailio[3035]: WARNING: tm [h_table.c:130]: free_cell_helper(): removed cell 0x7f232d4aff00 is still linked in hash table (h_table.c:440)
Nov 25 14:25:38 sip42 kamailio[3035]: WARNING: tm [h_table.c:130]: free_cell_helper(): removed cell 0x7f232d4b8b58 is still linked in hash table (h_table.c:440)
Nov 25 14:25:38 sip42 kamailio[3035]: WARNING: tm [h_table.c:130]: free_cell_helper(): removed cell 0x7f232d4b2720 is still linked in hash table (h_table.c:440)
Nov 25 14:25:38 sip42 kamailio[3035]: WARNING: tm [h_table.c:130]: free_cell_helper(): removed cell 0x7f232d4ab478 is still linked in hash table (h_table.c:440)
Nov 25 14:25:38 sip42 kamailio[3035]: WARNING: tm [h_table.c:130]: free_cell_helper(): removed cell 0x7f232d4b70f8 is still linked in hash table (h_table.c:440)
Nov 25 14:25:38 sip42 kamailio[3035]: WARNING: tm [h_table.c:130]: free_cell_helper(): removed cell 0x7f232d4a42e0 is still linked in hash table (h_table.c:440)
Nov 25 14:25:38 sip42 kamailio[3035]: WARNING: tm [h_table.c:130]: free_cell_helper(): removed cell 0x7f232d4ba200 is still linked in hash table (h_table.c:440)
Nov 25 14:25:38 sip42 kamailio[3035]: WARNING: tm [h_table.c:130]: free_cell_helper(): removed cell 0x7f232d4b55e0 is still linked in hash table (h_table.c:440)
```


```
(gdb) bt full
#0  strnlen () at ../sysdeps/x86_64/strlen.S:103
No locals.
#1  0x00007f2338de6b79 in _IO_vfprintf_internal (s=s@entry=0x7ffe89ef2d30, format=<optimized out>, 
    format@entry=0x7f232cbc3320 "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <%.*s>;tag=%.*s\r\nTo: <%.*s>;tag=%.*s\r\nCall-ID: %.*s\r\nCSeq: 1 OPTIONS\r\nContent-Length: 0\r\n\r\n", ap=ap@entry=0x7ffe89ef2e58) at vfprintf.c:1642
        len = <optimized out>
        string_malloced = <optimized out>
        step0_jumps = {0, -21408, -10006, -9919, -9825, -9738, -9633, -9357, -8392, -7901, -7780, -7036, -7329, -7232, -6868, -9131, -2198, -2183, -4523, -4438, -1471, -3815, -1799, 
          -4599, -168, -1104, -2074, -7135, -7232, -9460}
        space = 0
        is_short = 0
        use_outdigits = 0
        step1_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, -7901, -7780, -7036, -7329, -7232, -6868, -9131, -2198, -2183, -4523, -4438, -1471, -3815, -1799, -4599, -168, -1104, -2074, -7135, 
          -7232, 0}
        group = 0
        prec = 954104314
        step2_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -7780, -7036, -7329, -7232, -6868, -9131, -2198, -2183, -4523, -4438, -1471, -3815, -1799, -4599, -168, -1104, -2074, -7135, 
          -7232, 0}
        string = <optimized out>
        left = 0
        is_long_double = 0
        width = 0
        step3a_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -7133, 0, 0, 0, -6868, -9131, -2198, -2183, -4523, 0, 0, 0, 0, -4599, 0, 0, 0, 0, 0, 0}
        alt = 0
        showsign = 0
        is_long = 0
        is_char = 0
        pad = 32 ' '
        step3b_jumps = {0 <repeats 11 times>, -7329, 0, 0, -6868, -9131, -2198, -2183, -4523, -4438, -1471, -3815, -1799, -4599, -168, -1104, -2074, 0, 0, 0}
        step4_jumps = {0 <repeats 14 times>, -6868, -9131, -2198, -2183, -4523, -4438, -1471, -3815, -1799, -4599, -168, -1104, -2074, 0, 0, 0}
        is_negative = <optimized out>
        number = <optimized out>
        base = <optimized out>
        the_arg = {pa_wchar = 4284224 L'\x415f40', pa_int = 4284224, pa_long_int = 4284224, pa_long_long_int = 4284224, pa_u_int = 4284224, pa_u_long_int = 4284224, 
          pa_u_long_long_int = 4284224, pa_double = 2.1166878974885686e-317, pa_long_double = <invalid float value>, 
          pa_string = 0x415f40 <_start> "1\355I\211\321^H\211\342H\203\344\360PTI\307\300", 
          pa_wstring = 0x415f40 <_start> L"\x8949ed31\x89485ed1\xe48348e2\x495450f0\x2f00c0c7\xc748006e\x6e2e90c1\xc7c74800\x506a8b\xfff957e8\xf66f4ff䐟\x9d2eb7b8\x2d485500\x9d2eb0\xef88348\x76e58948렛\x85480000\x5d1174c0\x9d2eb0bf\x66e0ff00\x841f0f", pa_pointer = 0x415f40 <_start>, pa_user = 0x415f40 <_start>}
        spec = 62 '>'
        _buffer = {__routine = 0x7ffe89ef3650, __arg = 0x7f232d4ba200, __canceltype = 759931928, __prev = 0x100000000}
        _avail = <optimized out>
        thousands_sep = 0x0
        grouping = 0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>
        done = 134
        f = 0x7f232cbc3376 "s\r\nTo: <%.*s>;tag=%.*s\r\nCall-ID: %.*s\r\nCSeq: 1 OPTIONS\r\nContent-Length: 0\r\n\r\n"
        lead_str_end = <optimized out>
        end_of_spec = <optimized out>
        work_buffer = " )\357\211\376\177\000\000\244\026\347\065#\177\000\000\000\000\000\000\000\000\000\000\060.\357\211\376\177\000\000\340-\357\211\376\177\000\000A8\347\065#\177\000\000sip:5.150.\357\211\376\177\000\000p)\357\211\376\177\000\000\000\000\000\000ber_\300)\357\211\376\177\000\000\000\000\000\000nsumr\257J-#\177\000\000\000\000\000\000\000\000\000\000\060\060\000\000\376\177\000\000\372y\336\070#\177\000\000sip:+49402000@5.159.60.157:45850;ob8#\177\000\000X\024\030\000\000\000\000\000X\024\030\000\000\000\000\000\b\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000"...
        workstart = 0x7f22f6b55010 ""
        workend = 0x7f2323fff5b0 ""
        ap_save = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7ffe89ef2f30, reg_save_area = 0x7ffe89ef2e70}}
        nspecs_done = 1
        save_errno = <optimized out>
        readonly_format = 0
        args_malloced = 0x0
        specs = <optimized out>
        specs_malloced = false
        jump_table = "\001\000\000\004\000\016\000\006\000\000\a\002\000\003\t\000\005\b\b\b\b\b\b\b\b\b\000\000\000\000\000\000\000\032\000\031\000\023\023\023\000\035\000\000\f\000\000\000\000\000\000\025\000\000\000\000\022\000\r\000\000\000\000\000\000\032\000\024\017\023\023\023\n\017\034\000\v\030\027\021\026\f\000\025\033\020\000\000\022\000\r"
        __PRETTY_FUNCTION__ = "_IO_vfprintf_internal"
#2  0x00007f2338e0845b in __IO_vsprintf (
    string=0x7f232cdc7440 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <0.157:45850;ob SIP/2.0\r\nVia: SIP/2.0/UDP 5.159.56.76;br>;tag=", 
    format=0x7f232cbc3320 "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <%.*s>;tag=%.*s\r\nTo: <%.*s>;tag=%.*s\r\nCall-ID: %.*s\r\nCSeq: 1 OPTIONS\r\nContent-Length: 0\r\n\r\n", args=args@entry=0x7ffe89ef2e58) at iovsprintf.c:42
        sf = {_sbf = {_f = {_flags = -72515583, 
              _IO_read_ptr = 0x7f232cdc7440 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <0.157:45850;ob SIP/2.0\r\nVia: SIP/2.0/UDP 5.159.56.76;br>;tag=", 
              _IO_read_end = 0x7f232cdc7440 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <0.157:45850;ob SIP/2.0\r\nVia: SIP/2.0/UDP 5.159.56.76;br>;tag=", 
              _IO_read_base = 0x7f232cdc7440 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <0.157:45850;ob SIP/2.0\r\nVia: SIP/2.0/UDP 5.159.56.76;br>;tag=", 
              _IO_write_base = 0x7f232cdc7440 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <0.157:45850;ob SIP/2.0\r\nVia: SIP/2.0/UDP 5.159.56.76;br>;tag=", _IO_write_ptr = 0x7f232cdc74c6 <_faked_sip_msg_buf+134> "", _IO_write_end = 0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>, 
              _IO_buf_base = 0x7f232cdc7440 <_faked_sip_msg_buf> "OPTIONS sip:you@kamailio.org SIP/2.0\r\nVia: SIP/2.0/UDP 127.0.0.1\r\nFrom: <0.157:45850;ob SIP/2.0\r\nVia: SIP/2.0/UDP 5.159.56.76;br>;tag=", _IO_buf_end = 0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>, _IO_save_base = 0x0, _IO_backup_base = 0x0, _IO_save_end = 0x0, 
              _markers = 0x0, _chain = 0x0, _fileno = 1, _flags2 = 0, _old_offset = 0, _cur_column = 0, _vtable_offset = -128 '\200', _shortbuf = "", _lock = 0x0, _offset = 1047824, 
              _codecvt = 0x181f48, _wide_data = 0xffffffffffffffff, _freeres_list = 0x0, _freeres_buf = 0x2, _freeres_size = 1, _mode = -1, 
              _unused2 = "\000\000\000\000P6\357\211\376\177\000\000\000\000\000\000\000\000\000"}, vtable = 0x7f233913e760 <_IO_str_jumps>}, _s = {_allocate_buffer = 0x0, 
            _free_buffer = 0x575961 <run_actions+1572>}}
        ret = <optimized out>
#3  0x00007f2338decf17 in __sprintf (s=<optimized out>, format=<optimized out>) at sprintf.c:32
        arg = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7ffe89ef2f30, reg_save_area = 0x7ffe89ef2e70}}
        done = 48
#4  0x00007f232cbb4db2 in faked_msg_init_with_dlg_info (callid=0x7f232d4aa548, from_uri=0x7f232d4aa558, from_tag=0x7f232d4aa568, to_uri=0x7f232d4aa578, to_tag=0x7f232d4aa588, 
    msg=0x7ffe89ef2fe8) at cnxcc_sip_msg_faker.c:40
        __FUNCTION__ = "faked_msg_init_with_dlg_info"
#5  0x00007f232cba022b in terminate_call (call=0x7f232d4aa4e8) at cnxcc_mod.c:984
        dmsg = 0x0
        data = 0x7f232d4aa548
        __FUNCTION__ = "terminate_call"
        root = 0x7f232d090528
        result = 0x0
        node = 0x1
        node1 = 0x0
        end_dlg_cmd = 0x0
#6  0x00007f232cb9ee1a in terminate_all_calls (credit_data=0x7f232d4aa438) at cnxcc_mod.c:899
        call = 0x7f232d4aa4e8
        tmp = 0x7f232d4aa4e8
        __FUNCTION__ = "terminate_all_calls"
#7  0x00007f232cb8f56f in check_calls_by_money (ticks=105983065, param=0x0) at cnxcc_check.c:109
---Type <return> to continue, or q <return> to quit---
        credit_data = 0x7f232d4aa438
        call = 0x7f232d4aa4e8
        total_consumed_money = 10
        consumption_diff = 2
        h_entry = 0x7f232d4aa340
        tmp = 0x7f232d36cc00
        tmp_call = 0x7f232d4b5340
        i = 118
        __FUNCTION__ = "check_calls_by_money"
#8  0x00000000005bcf1c in fork_basic_timer (child_id=-1, desc=0x7f232cbbca3d "CNXCC TB TIMER", make_sock=1, f=0x7f232cb8e240 <check_calls_by_money>, param=0x0, interval=1)
    at timer_proc.c:79
        pid = 0
#9  0x00007f232cb9600e in __child_init (rank=0) at cnxcc_mod.c:383
        pid = 0
        __FUNCTION__ = "__child_init"
#10 0x00000000005143d4 in init_mod_child (m=0x7f23386068a8, rank=0) at sr_module.c:915
        __FUNCTION__ = "init_mod_child"
#11 0x00000000005146db in init_child (rank=0) at sr_module.c:941
No locals.
#12 0x0000000000505cef in main_loop () at main.c:1654
        i = 4
        pid = 3071
        si = 0x0
        si_desc = "udp receiver child=3 sock=127.0.0.1:5060\000\061\000\061#\177\000\000\300\063\357\211\376\177\000\000\a\254\360\061#\177\000\000y%p\000\000\000\000\000\310\025\067-#\177\000\000\220\224\364\061#\177\000\000\300\230o8#\177\000\000\000i\364\061#\177\000\000\003\000\000\000#\177\000\000P3\357\211\376\177\000\000xBI\000\000\000\000"
        nrprocs = 4
        __FUNCTION__ = "main_loop"
#13 0x000000000050be5a in main (argc=13, argv=0x7ffe89ef3658) at main.c:2553
        cfg_stream = 0x2952010
        c = -1
        r = 0
        tmp = 0x7ffe89ef3ee2 ""
        tmp_len = 32547
        port = 964122064
        proto = 0
        options = 0x71cae0 ":f:cm:M:dVIhEeb:l:L:n:vKrRDTN:W:w:t:u:g:P:G:SQ:O:a:A:"
        ret = -1
        seed = 3342281071
        rfd = 4
        debug_save = 0
        debug_flag = 0
        dont_fork_cnt = 0
        n_lst = 0xf63d4e2e
        p = 0x7f2339775000 ""
        st = {st_dev = 15, st_ino = 9426, st_nlink = 2, st_mode = 16877, st_uid = 109, st_gid = 114, __pad0 = 0, st_rdev = 0, st_size = 40, st_blksize = 4096, st_blocks = 0, 
          st_atim = {tv_sec = 1448455582, tv_nsec = 935958015}, st_mtim = {tv_sec = 1448455221, tv_nsec = 503961461}, st_ctim = {tv_sec = 1448455221, tv_nsec = 503961461}, 
          __glibc_reserved = {0, 0, 0}}
        __FUNCTION__ = "main"
```

**Comment by miconda** [comment]
As expected, just some safety checks are not enough, looks like the entire call structure is invalid at that point. Maybe @caruizdiaz, the developer of the module, has the time to check and see if it spots where the issue is.

**Comment by miconda** [comment]
One more thing that you can do to help troubleshooting is to run kamailio with 'debug=3' in config and paste all log messages here, from the beginning of the call (initial INVITE), till the crash.

**Comment by miconda** [comment]
Any testing done with debug=3?

**Comment by clecny** [comment]
We use cnxcc and would like to know if this is still an issue before updating to 4.3.3 .  
4.2.x is safer ? really appreciate if someone can update this issue.

**Comment by miconda** [comment]
Another issue (#407) related to cnxcc was closed by the reporter as no longer valid for latest version. Maybe this one need to be retested with latest version. Also there was no follow up with debug=3 that was asked on Nov 26.

**Comment by grumvalski** [comment]
The issue should be solved by https://github.com/kamailio/kamailio/commit/d0bdaa7567240b18794ab7512b09a55767c44240.
The fix has been backported to 4.3 and 4.4 branches.
